export const GAME_STATUSES = {
    SETTINGS: 'settings',
    IN_PROGRESS: 'in_progress',
    WIN: 'win',
    LOOSE: 'loose'
}

export const EVENTS = {
    GAME_STARTED: 'GAME_STARTED',
    CHEESE_JUMPED: 'CHEESE_JUMPED',
    PLAYER1_MOVED: 'PLAYER1_MOVED',
    PLAYER2_MOVED: 'PLAYER2_MOVED',
    STATUS_CHANGED: 'STATUS_CHANGED',
    SCORES_CHANGED: 'SCORES_CHANGED',
    CHEESE_CAUGHT: 'CHEESE_CAUGHT',
    SETTING_CHANGED: 'SETTING_CHANGED',
    PLAYER_WIN: 'PLAYER_WIN',
    CHEESE_WIN: 'CHEESE_WIN',
}

export const MOVING_DIRECTIONS = {
    UP: 'UP',
    DOWN: 'DOWN',
    RIGHT: 'RIGHT',
    LEFT: 'LEFT'
}
